### ISSUE TITLE
Simple Email Service - Signature does not match

### ISSUE THREAD

**Issue by damir-sirola** [noppoMan/aws-sdk-swift#45]
Hi, thanks for the great library, but I'm having an issue with Email service.
When I try to send an email I get the following error:
```
signatureDoesNotMatch(Optional("The request signature we calculated does not match the
signature you provided. Check your AWS Secret Access Key and signing method. Consult the
service documentation for details.
```

I'm using the following code to initialize the service and send the request:
```Swift
        let emailService = AWSSDKSwift.Email(accessKeyId: accessKey, secretAccessKey: secretKey,
                 region: .euwest1, endpoint: "https://email.eu-west-1.amazonaws.com")
        let destination = AWSSDKSwift.Email.Destination(toAddresses: [email.to])
        let message =
            AWSSDKSwift.Email.Message(
                body: AWSSDKSwift.Email.Body(
                    text: AWSSDKSwift.Email.Content(data: "Test")
                ),
                subject: AWSSDKSwift.Email.Content(
                    data: email.subject
                )
            )
        let emailRequest = AWSSDKSwift.Email.SendEmailRequest(
            destination: destination,
            message: message,
            source: email.from
        )
        do {
            let result = try emailService.sendEmail(emailRequest)
        } catch { 
            ...
        }
```

Both `email.to` and `email.from` are validated emails.
I tried different access key and secret key always making sure they have AmazonSESFullAccess policy.
I haven't tried using any other service yet.

**Comment by noppoMan** [comment]
@damir-sirola 
I'll check that! Actually I didn't tests for all services..

**Comment by damir-sirola** [comment]
That's ok, it would be quite hard and time-consuming to test everything. Thank you for fast response :)

**Comment by noppoMan** [comment]
@damir-sirola 
Sorry for late replying.
i just fixed this error case with https://github.com/noppoMan/aws-sdk-swift-core/pull/4 and https://github.com/noppoMan/aws-sdk-swift-core/pull/5.
Could you try this again? with `swift package update` before running program.

**Comment by damir-sirola** [comment]
@noppoMan It works perfectly now. Thank you for such a quick fix and keep up the good work 🙂
