### ISSUE TITLE
kinesis sdk stand alone package

### ISSUE THREAD

**Issue by jonnymacs** [noppoMan/aws-sdk-swift#64]
Hello Yuki,

I have done this manually using the latest kinesis sdk from this repo and tested a putRecord successfully. Would you mind creating an official repo for the kinesis sdk in the swift-aws organization?

https://github.com/swift-aws/kinesis

**Comment by noppoMan** [comment]
@jonnymacs 
Thanks for using aws-sdk-swift! 

I just created https://github.com/swift-aws/kinesis repo. Check it out.
I can help you if you find any issues or bugs in it.

**Comment by jonnymacs** [comment]
Thanks Yuki! You're welcome, thanks for building this great library for swift!

I am able to pull with `.branch("master")`, and it is working 👍 

But I think we'll need to tag a version to use `.upToNextMajor(from: "1.0.0")`

**Comment by jonnymacs** [comment]
👍 good to go. Thank you!
